/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AgentApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AgentData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AgentMapping": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Create": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Fetch": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Remove": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Start": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Update": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}